POST http://localhost:3001/api/adminCreate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjQwNWI5MmMxMTVjYmUxNjg3N2RiMTY5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc4MDk3MjI3LCJleHAiOjE2NzgxMDA4Mjd9.Orsks5NuYeg9MraHHEYmLOTzHEOXwAPKgELbOAkpIDM

{
    "email": "Johnnyboy@gmail.com",
    "name": "John Doe Doe Doe DOe DOe",
    "password": "123456",
    "role": "admin"
}