DELETE http://localhost:3001/api/ips/
Content-Type: application/json
Authorization: Bearer

{
  "ids": [
    "641af4ece4e2cf1434d442fa",
    "641af4ece4e2cf1434d442fb",
    "641af4ece4e2cf1434d442fc"
  ]
}