PUT http://localhost:3001/api/ips/next-ip/6405a36629a4da06839c6726
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWQiOiI2NDA1OWFjMzkyMjhmMzA4ZjQ0YjU0NWYiLCJpYXQiOjE2NzgwODk3MzMsImV4cCI6MTY3ODA5MzMzM30.QA-zs1IUTmJ7z-JPMUCGHbvlJz11w4yXNJxD9l_XQfo

{
  "TTL" : 2
}