DELETE http://localhost:3001/api/users/640ed0fd6ffd87f0abfbb935
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjQwZWQwNGM3YWNhMjlkNzEyNDhkMDFkIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc4NjkyNTcyLCJleHAiOjE2Nzg2OTYxNzJ9.Nt69euRP_RJ4LIgilZ_LlkBen88K_4mKIuKbH6Cr5sY
