DELETE http://localhost:3001/api/users/640844c435a0a7d6ac50f889
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjQwODQyYTkzNWEwYTdkNmFjNTBmODU5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc4MjYzNjg2LCJleHAiOjE2NzgyNjcyODZ9.WD9MmXIRj7oakz3O7EVsqXpOj5Q0P9BuCLKu7GQf9Sk