GET http://localhost:3001/api/users/640ecfcd0b015976f9b603e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWQiOiI2NDBlY2ZjZDBiMDE1OTc2ZjliNjAzZTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTY3ODY5Mzk5MywiZXhwIjoxNjc4Njk3NTkzfQ.2F_z7FgopiNoVQdhpSZJRYkG5ormsSTqML_UYmymgiM