POST http://localhost:3001/api/admin/network
Content-Type: application/json
Authorization: Bearer 

{
  "networkName": "my network 2",
  "hostMin": "200.168.1.1",
  "hostMax": "200.168.1.255",
  "hostNetwork": 24,
  "networkActive": false
}