POST http://localhost:3001/api/admin/network
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjQxMmRhYzYwZWM1ZDRlYTNlZGNkNDgxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc5Mzg2ODA1LCJleHAiOjE2NzkzOTA0MDV9.S3xFvOQgEw6PmQSx-CWm8gGln9V9acL2Np08zZIPdFA

{
  "networkName": "my network 2",
  "hostMin": "200.168.1.1",
  "hostMax": "200.168.1.255",
  "hostNetwork": 24,
  "networkActive": false
}