POST http://localhost:3001/api/ips/next-ip
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWQiOiI2NDBlZDhjNDVkYmJjOTFmM2FmYWY0Y2UiLCJyb2xlIjoidXNlciIsImlhdCI6MTY3ODY5NTQ2MSwiZXhwIjoxNjc4Njk5MDYxfQ.EAYWeYV7unkIuNtZeVRi5IRXJ8dwvIb-VlnsL5nr2fg

{
  "desc" : "Kuvaus 1",
  "networkId" : "640ed0747aca29d71248d021"
}