POST http://localhost:3001/api/users/passwordChange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRpQGdtYWlsLmNvbSIsImlkIjoiNjNmZTYxY2ZhMTE4NWM4MDRmZjMzZGFlIiwiaWF0IjoxNjc3NzQ2MDE0LCJleHAiOjE2Nzc3NDk2MTR9.GyH3znea-F19Vu8FznISX_kL2mJ9dwbb5wPTZ_Ub4VI

  {
    "oldPassword": "1235",
    "newPassword": "1234"
  }
