POST http://localhost:3001/api/users/passwordChange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWQiOiI2NDA5OTIwYzBlMTMyNGRkNWFiN2MwMmQiLCJyb2xlIjoidXNlciIsImlhdCI6MTY3ODM1MDIyNSwiZXhwIjoxNjc4MzUzODI1fQ.ZbKlNN2wj51vLPPkd0WJq1_4WaVnp9-Yv4-M_-1Fbrw

  {
    "oldPassword": "3",
    "newPassword": "1"
  }
